// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhM84-b6C7Ag2_8zyzuenvIMCYhgNjS3M',
    appId: '1:160775260213:web:f80782765a1e2fe280097c',
    messagingSenderId: '160775260213',
    projectId: 'property-manager-bbb5e',
    authDomain: 'property-manager-bbb5e.firebaseapp.com',
    storageBucket: 'property-manager-bbb5e.appspot.com',
    measurementId: 'G-TCK6MVQ0W9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK0hQvEzuqp2TRjL0GeJUwdAXlfQ2dLHQ',
    appId: '1:160775260213:android:0cd163e325bd009480097c',
    messagingSenderId: '160775260213',
    projectId: 'property-manager-bbb5e',
    storageBucket: 'property-manager-bbb5e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhldRjvSEMZ0jCy-Vz7cjQo_K_LJrRlxQ',
    appId: '1:160775260213:ios:87e7c9862116212780097c',
    messagingSenderId: '160775260213',
    projectId: 'property-manager-bbb5e',
    storageBucket: 'property-manager-bbb5e.appspot.com',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhldRjvSEMZ0jCy-Vz7cjQo_K_LJrRlxQ',
    appId: '1:160775260213:ios:87e7c9862116212780097c',
    messagingSenderId: '160775260213',
    projectId: 'property-manager-bbb5e',
    storageBucket: 'property-manager-bbb5e.appspot.com',
    iosBundleId: 'com.example.admin',
  );
}
